#!/bin/bash
# cloudstart    Init script for running cloudstart 
#
# Author:       Jason Hancock <jsnbyh@gmail.com>
#
# chkconfig: - 75 02
#
# description: Configures cloud images 
# processname: cloudstart
# config: /etc/sysconfig/cloudstart

# Source function library.
. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/cloudstart ]; then
    . /etc/sysconfig/cloudstart
fi

LOCKFILE=/var/lock/subsys/cloustart

start() {

    TMP_FILE=`mktemp`
    for f in $PLUGINS
    do
        $PLUGINS_DIR/$f $TMP_FILE
    done
    rm -f $TMP_FILE

    touch $LOCKFILE

    action $"Starting cloudstart: " /bin/true
    RETVAL=0
}

stop() {
    # There's really noting to do when we stop it. We only want cloudstart
    # to ever run only once at boot. If you want to run it again, you can
    # just call 'start' again and it will run
    action $"Stopping cloudstart: " /bin/true
    RETVAL=0
}

status() {
    if [ -f $LOCKFILE ];
    then
        echo "cloudstart has run"
        RETVAL=0
    else
        echo "cloudstart has not run"
        RETVAL=1
    fi
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    status)
        status
    ;;
    *)
        echo $"Usage: $0 {start|stop|status}"
        exit 1
esac

exit $RETVAL

