#!/usr/bin/perl

use strict;
use warnings;

open IN, "<$ARGV[0]" or die("Can't open $ARGV[0] for input");
my %data;

# Load up the user-data
while(my $line=<IN>){
    chomp($line);
    if($line=~m/^(.+?)=(.+)$/) {
        $data{$1} = $2;
    }
}
close IN;

if(defined($data{'hostname'})) {
    system("hostname",  $data{'hostname'});
}
